In [73]:
import numpy as np
import pandas as pd
from pandas import Series, DataFrame

# 5.1 Introduction to pandas Data Structures

### Series

A Series is a one-dimensional array-like object containing a sequence of values (of similar types to NumPy types) of the same type and an associated array of data labels, called its index.

Another way to think about a Series is as a fixed-length, ordered dictionary, as it is a mapping of index values to data values. It can be used in many contexts where you might use a dictionary

In [74]:
obj = pd.Series([4, 7, -5, 3])

In [75]:
obj

0    4
1    7
2   -5
3    3
dtype: int64

In [76]:
obj.array

<NumpyExtensionArray>
[np.int64(4), np.int64(7), np.int64(-5), np.int64(3)]
Length: 4, dtype: int64

In [77]:
obj.index

RangeIndex(start=0, stop=4, step=1)

In [78]:
obj2 = pd.Series([4, 7, -5, 3], index=["d", "b", "a", "c"])
obj2

d    4
b    7
a   -5
c    3
dtype: int64

In [79]:
obj2.index

Index(['d', 'b', 'a', 'c'], dtype='object')

In [80]:
#using the index to get the value associated with
obj2["a"]

np.int64(-5)

In [81]:
obj2["c"]

np.int64(3)

In [82]:
obj2[["c", "a", "d"]]

c    3
a   -5
d    4
dtype: int64

In [83]:
#index value link is maintained even after applying functions


In [84]:
#boolean array
obj2[obj2 > 0]

d    4
b    7
c    3
dtype: int64

In [85]:
#scalar multiplication
obj2 * 2

d     8
b    14
a   -10
c     6
dtype: int64

In [86]:
#math function
np.exp(obj2)

d      54.598150
b    1096.633158
a       0.006738
c      20.085537
dtype: float64

In [87]:
"b" in obj2

True

In [88]:
"c" in obj2

True

In [89]:
"e" in obj2

False

In [90]:
#from a Python dict 
sdata = {"Ohio": 35000, "Texas": 71000, "Oregon": 16000, "Utah": 5000}

#to a pandas Series
obj3 = pd.Series(sdata)
obj3

Ohio      35000
Texas     71000
Oregon    16000
Utah       5000
dtype: int64

In [91]:
#and back to a Python dict
obj3.to_dict()

{'Ohio': 35000, 'Texas': 71000, 'Oregon': 16000, 'Utah': 5000}

In [92]:
#cool

In [93]:
#overriding default key value placement with your own order
#the new index
states = ["California", "Ohio", "Oregon", "Texas"]

In [94]:
#placing the states into series as its index
obj4 = pd.Series(sdata, index=states)
obj4

California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64

In [95]:
#notice California is NaN and Utah has been left behind

In [96]:
#isna and notna
#which is missing a value and vice versa
pd.isna(obj4)

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

In [97]:
pd.notna(obj4)

California    False
Ohio           True
Oregon         True
Texas          True
dtype: bool

In [98]:
#Series has isna and notna as instance methods
obj4.isna()

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

### Data Alignment - like a join

In [99]:
obj3

Ohio      35000
Texas     71000
Oregon    16000
Utah       5000
dtype: int64

In [100]:
obj4

California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64

In [101]:
obj3 + obj4


California         NaN
Ohio           70000.0
Oregon         32000.0
Texas         142000.0
Utah               NaN
dtype: float64

In [102]:
#looks like a full join to me, includes what is in both AND what is missing.

In [103]:
#Both Series and its index has a name attribute.
#Can change their names
obj4.name = "population"
obj4.index.name = "state"
obj4

state
California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
Name: population, dtype: float64

In [104]:
#Changing a Series index IN ONE LINE
obj

0    4
1    7
2   -5
3    3
dtype: int64

In [105]:
obj.index = ["Bob", "Steve", "Jeff", "Ryan"]
obj

Bob      4
Steve    7
Jeff    -5
Ryan     3
dtype: int64

### DataFrame

In [106]:
data = {"state": ["Ohio", "Ohio", "Ohio", "Nevada", "Nevada", "Nevada"],
        "year": [2000, 2001, 2002, 2001, 2002, 2003],
        "pop": [1.5, 1.7, 3.6, 2.4, 2.9, 3.2]
    
}

frame = pd.DataFrame(data)
frame

state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9
5  Nevada  2003  3.2

In [107]:
#first five rows
frame.head()

state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9

In [108]:
#last five rows
frame.tail()

state  year  pop
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9
5  Nevada  2003  3.2

In [109]:
#rearranging columns
pd.DataFrame(data, columns=["year", "state", "pop"])

year   state  pop
0  2000    Ohio  1.5
1  2001    Ohio  1.7
2  2002    Ohio  3.6
3  2001  Nevada  2.4
4  2002  Nevada  2.9
5  2003  Nevada  3.2

In [110]:
#adding a new column without rows
frame2 = pd.DataFrame(data, columns=["year", "state", "pop", "debt"])

In [111]:
frame2.columns

Index(['year', 'state', 'pop', 'debt'], dtype='object')

In [112]:
#retrieving a DataFrame column as a Series
#can be used with any column
frame2["state"]

0      Ohio
1      Ohio
2      Ohio
3    Nevada
4    Nevada
5    Nevada
Name: state, dtype: object

In [113]:
#dot notation only for column names with a valid Python variable name that doesnt conflict with methods in the dataframe
frame2.year

0    2000
1    2001
2    2002
3    2001
4    2002
5    2003
Name: year, dtype: int64

In [114]:
#grabbing rows in a DataFrame
#iloc and loc

#grabs row at index 1
frame2.loc[1]

year     2001
state    Ohio
pop       1.7
debt      NaN
Name: 1, dtype: object

In [115]:
#grabs row at index 2
frame2.loc[2]

year     2002
state    Ohio
pop       3.6
debt      NaN
Name: 2, dtype: object

In [116]:
#changing column values by assignment

#scalar value
frame2["debt"] = 16.5
frame2

year   state  pop  debt
0  2000    Ohio  1.5  16.5
1  2001    Ohio  1.7  16.5
2  2002    Ohio  3.6  16.5
3  2001  Nevada  2.4  16.5
4  2002  Nevada  2.9  16.5
5  2003  Nevada  3.2  16.5

In [117]:
#an array of values w a range
frame2["debt"] = np.arange(6.)
frame2

year   state  pop  debt
0  2000    Ohio  1.5   0.0
1  2001    Ohio  1.7   1.0
2  2002    Ohio  3.6   2.0
3  2001  Nevada  2.4   3.0
4  2002  Nevada  2.9   4.0
5  2003  Nevada  3.2   5.0

In [118]:
#the assigned list or array must be the same length of the DataFrame

val = pd.Series([-1.2, -1.5, -1.7], index=[2, 4, 5])
frame2["debt"] = val
frame2

year   state  pop  debt
0  2000    Ohio  1.5   NaN
1  2001    Ohio  1.7   NaN
2  2002    Ohio  3.6  -1.2
3  2001  Nevada  2.4   NaN
4  2002  Nevada  2.9  -1.5
5  2003  Nevada  3.2  -1.7

In [119]:
#del method removes columns

#first create eastern column
frame2["eastern"] = frame2["state"] == "Ohio"
frame2

year   state  pop  debt  eastern
0  2000    Ohio  1.5   NaN     True
1  2001    Ohio  1.7   NaN     True
2  2002    Ohio  3.6  -1.2     True
3  2001  Nevada  2.4   NaN    False
4  2002  Nevada  2.9  -1.5    False
5  2003  Nevada  3.2  -1.7    False

In [120]:
#then delete it
#now eastern is gone
del frame2["eastern"]
frame2.columns

Index(['year', 'state', 'pop', 'debt'], dtype='object')

In [121]:
#nested dictionary of dictionaries
populations = {"Ohio": {2000: 1.5, 2001: 1.7, 2002: 3.6},
               "Nevada": {2001: 2.4, 2002: 2.9}}

In [122]:
#Outer dict keys will be columns and inner keys as the row index
frame3 = pd.DataFrame(populations)
frame3

Ohio  Nevada
2000   1.5     NaN
2001   1.7     2.4
2002   3.6     2.9

In [123]:
#rotate the table with .T
frame3.T

2000  2001  2002
Ohio     1.5   1.7   3.6
Nevada   NaN   2.4   2.9

In [124]:
#inception -- a dictionary of Series
pdata = {"Ohio": frame3["Ohio"][:-1],
         "Nevada": frame3["Nevada"][:2]
        }
pd.DataFrame(pdata)

Ohio  Nevada
2000   1.5     NaN
2001   1.7     2.4

In [125]:
#setting the name of index and columns
frame3.index.name = "year"
frame3.columns.name = "state"
frame3

state  Ohio  Nevada
year               
2000    1.5     NaN
2001    1.7     2.4
2002    3.6     2.9

In [126]:
#DataFrame does not have name as an attribute
#.tonumpy()
#turns DataFrame into a 2d ndarray

frame3.to_numpy()

array([[1.5, nan],
       [1.7, 2.4],
       [3.6, 2.9]])

In [127]:
frame2.to_numpy()

array([[2000, 'Ohio', 1.5, nan],
       [2001, 'Ohio', 1.7, nan],
       [2002, 'Ohio', 3.6, -1.2],
       [2001, 'Nevada', 2.4, nan],
       [2002, 'Nevada', 2.9, -1.5],
       [2003, 'Nevada', 3.2, -1.7]], dtype=object)

### Index Objects

#### Index Methods and properties

* append()   Concatentate index objects, producing a new index
* difference() Compute set differences as Index
* intersection() Compute set intersection
* union()  Compute set union
* isin()   Boolean array showing if each value is inside a collection
* delete() 
* drop()
* insert()
* is_monotonic()
* is_unique()
* unique()  

In [128]:
obj = pd.Series(np.arange(3), index=["a", "b","c"])
index = obj.index
index

Index(['a', 'b', 'c'], dtype='object')

In [129]:
index[1:]

Index(['b', 'c'], dtype='object')

In [130]:
#index objects are immutable
index[1] = "d"

TypeError: Index does not support mutable operations

In [131]:
labels = pd.Index(np.arange(3))
labels

Index([0, 1, 2], dtype='int64')

In [132]:
obj2 = pd.Series([1.5, -2.5, 0], index=labels)
obj2

0    1.5
1   -2.5
2    0.0
dtype: float64

In [133]:
obj2.index is labels

True

In [134]:
frame3

state  Ohio  Nevada
year               
2000    1.5     NaN
2001    1.7     2.4
2002    3.6     2.9

In [135]:
frame3.columns

Index(['Ohio', 'Nevada'], dtype='object', name='state')

In [136]:
"Ohio" in frame3.columns

True

In [137]:
2003 in frame3.index

False

In [138]:
pd.Index(["foo", "foo", "bar", "bar"])

Index(['foo', 'foo', 'bar', 'bar'], dtype='object')

### 5.2 Essential Functionality

Reindexing

In [139]:
obj = pd.Series([4.5, 7.2, -5.3, 3.6], index=["d","b","a","c"])

In [140]:
obj

d    4.5
b    7.2
a   -5.3
c    3.6
dtype: float64

In [141]:
obj2 = obj.reindex(["a","b","c","e"])
obj2

a   -5.3
b    7.2
c    3.6
e    NaN
dtype: float64

In [142]:
obj3 = pd.Series(["blue", "purple", "yellow"], index=[0, 2, 4])
obj3

0      blue
2    purple
4    yellow
dtype: object

In [143]:
obj3.reindex(np.arange(6), method="ffill")

0      blue
1      blue
2    purple
3    purple
4    yellow
5    yellow
dtype: object

In [144]:
frame = pd.DataFrame(np.arange(9).reshape((3, 3)), index=["a","c","d"], columns=["Ohio", "Texas", "California"])

In [145]:
frame

Ohio  Texas  California
a     0      1           2
c     3      4           5
d     6      7           8

In [146]:
frame2 = frame.reindex(["a", "b", "c",])
frame2

Ohio  Texas  California
a   0.0    1.0         2.0
b   NaN    NaN         NaN
c   3.0    4.0         5.0

In [147]:
states = ["Texas", "Utah", "California"]
frame.reindex(columns=states)

Texas  Utah  California
a      1   NaN           2
c      4   NaN           5
d      7   NaN           8

In [148]:
frame.reindex(states, axis="columns")

Texas  Utah  California
a      1   NaN           2
c      4   NaN           5
d      7   NaN           8

In [149]:
frame.loc[["a", "d", "c"], ["California", "Texas"]]

California  Texas
a           2      1
d           8      7
c           5      4

### Dropping Entries from an Axis

In [150]:
obj = pd.Series(np.arange(5.), index=["a", "b", "c", "d", "e"])

In [151]:
obj

a    0.0
b    1.0
c    2.0
d    3.0
e    4.0
dtype: float64

In [152]:
new_obj = obj.drop("c")
new_obj

a    0.0
b    1.0
d    3.0
e    4.0
dtype: float64

In [153]:
obj.drop(["d", "c"])

a    0.0
b    1.0
e    4.0
dtype: float64

In [154]:
data = pd.DataFrame(np.arange(16).reshape((4,4)),
                    index=["Ohio", "Colorado", "Utah", "New York"],
                    columns=["one", "two", "three", "four"])
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [155]:
data.drop(index=["Colorado", "Ohio"])

one  two  three  four
Utah        8    9     10    11
New York   12   13     14    15

In [156]:
data.drop(columns=["two"])

one  three  four
Ohio        0      2     3
Colorado    4      6     7
Utah        8     10    11
New York   12     14    15

In [157]:
data.drop("two", axis=1)

one  three  four
Ohio        0      2     3
Colorado    4      6     7
Utah        8     10    11
New York   12     14    15

In [158]:
data.drop(["two", "four"], axis="columns")

one  three
Ohio        0      2
Colorado    4      6
Utah        8     10
New York   12     14

### Indexing, Selection, Filtering

In [159]:
obj = pd.Series(np.arange(4.), index=["a", "b", "c", "d"])
obj

a    0.0
b    1.0
c    2.0
d    3.0
dtype: float64

In [160]:
obj["b"]

np.float64(1.0)

In [161]:
obj[1]

/var/folders/j5/3rry1w9s6819d90x12dk94gr0000gq/T/ipykernel_4536/2469632899.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  obj[1]


np.float64(1.0)

In [162]:
obj[["b", "a", "d"]]

b    1.0
a    0.0
d    3.0
dtype: float64

In [163]:
obj[[1, 3]]

/var/folders/j5/3rry1w9s6819d90x12dk94gr0000gq/T/ipykernel_4536/2982346117.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  obj[[1, 3]]


b    1.0
d    3.0
dtype: float64

In [164]:
obj[obj < 2]

a    0.0
b    1.0
dtype: float64

In [165]:
obj.loc[["b", "a", "d"]]

b    1.0
a    0.0
d    3.0
dtype: float64

In [166]:
obj1 = pd.Series([1, 2, 3], index=[2, 0, 1])

In [167]:
obj2 = pd.Series([1, 2, 3], ["a", "b", "c"])

In [168]:
obj

a    0.0
b    1.0
c    2.0
d    3.0
dtype: float64

In [169]:
obj2

a    1
b    2
c    3
dtype: int64

In [170]:
obj1.iloc[[0, 1, 2]]

2    1
0    2
1    3
dtype: int64

In [171]:
obj2[[0, 1, 2]]

/var/folders/j5/3rry1w9s6819d90x12dk94gr0000gq/T/ipykernel_4536/2599987575.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  obj2[[0, 1, 2]]


a    1
b    2
c    3
dtype: int64

In [172]:
obj2.loc["b":"c"] = 5
obj2

a    1
b    5
c    5
dtype: int64

In [173]:
data = pd.DataFrame(np.arange(16).reshape(4,4),
                   index=["Ohio", "Colorado", "Utah", "New York"],
                   columns=["one", "two", "three", "four"])
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [174]:
data["two"]

Ohio         1
Colorado     5
Utah         9
New York    13
Name: two, dtype: int64

In [175]:
data[["three", "one"]]

three  one
Ohio          2    0
Colorado      6    4
Utah         10    8
New York     14   12

In [176]:
data[:2]

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7

In [177]:
data[data["three"] > 5]

one  two  three  four
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [178]:
data < 5

one    two  three   four
Ohio       True   True   True   True
Colorado   True  False  False  False
Utah      False  False  False  False
New York  False  False  False  False

In [179]:
data[data < 5] = 0
data

one  two  three  four
Ohio        0    0      0     0
Colorado    0    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

#### Selection on DataFrame with loc and iloc

In [180]:
data

one  two  three  four
Ohio        0    0      0     0
Colorado    0    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [181]:
data.loc["Colorado"]

one      0
two      5
three    6
four     7
Name: Colorado, dtype: int64

In [182]:
data.loc["Colorado", ["two", "three"]]

two      5
three    6
Name: Colorado, dtype: int64

In [183]:
data.iloc[2]

one       8
two       9
three    10
four     11
Name: Utah, dtype: int64

In [184]:
data.iloc[[2, 1]]

one  two  three  four
Utah        8    9     10    11
Colorado    0    5      6     7

In [185]:
data.iloc[[1,2], [3, 0, 1]]

four  one  two
Colorado     7    0    5
Utah        11    8    9

In [186]:
data.loc[:"Utah", "two"]

Ohio        0
Colorado    5
Utah        9
Name: two, dtype: int64

In [187]:
data.iloc[:, :3][data.three > 5]

one  two  three
Colorado    0    5      6
Utah        8    9     10
New York   12   13     14

In [188]:
#Boolean arrays
data.loc[data.three >= 2]

one  two  three  four
Colorado    0    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

Indexing options with DataFrame

* df[column]	Select single column or sequence of columns from the DataFrame; special case conveniences: Boolean array (filter rows), slice (slice rows), or Boolean DataFrame (set values based on some criterion)
* df.loc[rows]	Select single row or subset of rows from the DataFrame by label
* df.loc[:, cols]	Select single column or subset of columns by label
* df.loc[rows, cols]	Select both row(s) and column(s) by label
* df.iloc[rows]	Select single row or subset of rows from the DataFrame by integer position
* df.iloc[:, cols]	Select single column or subset of columns by integer position
* df.iloc[rows, cols]	Select both row(s) and column(s) by integer position
* df.at[row, col]	Select a single scalar value by row and column label
* df.iat[row, col]	Select a single scalar value by row and column position (integers)
* reindex method	Select either rows or columns by labels

### Integer indexing pitfalls

In [189]:
#no
ser = pd.Series(np.arange(3.))
ser

0    0.0
1    1.0
2    2.0
dtype: float64

In [190]:
# a no-no
ser[-1]

KeyError: -1

In [191]:
ser

0    0.0
1    1.0
2    2.0
dtype: float64

In [192]:
ser2 = pd.Series(pd.Series(np.arange(3.), index=["a", "b", "c"]))
ser2.iloc[-1]

np.float64(2.0)

In [193]:
ser.iloc[-1]

np.float64(2.0)

In [194]:
ser[:2]

0    0.0
1    1.0
dtype: float64

### Pitfalls with chained indexing

In [195]:
data.loc[:, "one"] = 1
data

one  two  three  four
Ohio        1    0      0     0
Colorado    1    5      6     7
Utah        1    9     10    11
New York    1   13     14    15

In [196]:
data.iloc[2] = 5
data

one  two  three  four
Ohio        1    0      0     0
Colorado    1    5      6     7
Utah        5    5      5     5
New York    1   13     14    15

In [197]:
data.loc[data["four"] > 5] = 3
data

one  two  three  four
Ohio        1    0      0     0
Colorado    3    3      3     3
Utah        5    5      5     5
New York    3    3      3     3

In [198]:
# a no-no
data.loc[data.three == 5] ["three"] = 6

/var/folders/j5/3rry1w9s6819d90x12dk94gr0000gq/T/ipykernel_4536/4190591945.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data.loc[data.three == 5] ["three"] = 6


In [199]:
data

one  two  three  four
Ohio        1    0      0     0
Colorado    3    3      3     3
Utah        5    5      5     5
New York    3    3      3     3

In [200]:
#do this instead
data.loc[data.three == 5, "three"] = 6
data

one  two  three  four
Ohio        1    0      0     0
Colorado    3    3      3     3
Utah        5    5      6     5
New York    3    3      3     3

## Arithmetic and Data Alignment

In [201]:
s1 = pd.Series([7.3, -2.5, 3.4, 1.5], index=["a", "c", "d", "e"])
s2 = pd.Series([-1.2, 3.6, -1.5, 4, 3.1],
              index=["a","c","e","f","g"])

In [202]:
s1

a    7.3
c   -2.5
d    3.4
e    1.5
dtype: float64

In [203]:
s2

a   -1.2
c    3.6
e   -1.5
f    4.0
g    3.1
dtype: float64

In [204]:
s1 + s2

a    6.1
c    1.1
d    NaN
e    0.0
f    NaN
g    NaN
dtype: float64

In [205]:
df1 = pd.DataFrame(np.arange(9.).reshape((3, 3)), columns=list("bcd"),
                   index=["Ohio", "Texas", "Colorado"])
df2 = pd.DataFrame(np.arange(12.).reshape((4, 3)), columns=list("bcd"),
                   index=["Utah", "Ohip", "Texas", "Oregon"])


In [206]:
df1

b    c    d
Ohio      0.0  1.0  2.0
Texas     3.0  4.0  5.0
Colorado  6.0  7.0  8.0

In [207]:
df2

b     c     d
Utah    0.0   1.0   2.0
Ohip    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [208]:
df1 + df2

b     c     d
Colorado  NaN   NaN   NaN
Ohio      NaN   NaN   NaN
Ohip      NaN   NaN   NaN
Oregon    NaN   NaN   NaN
Texas     9.0  11.0  13.0
Utah      NaN   NaN   NaN

In [209]:
df1 = pd.DataFrame({"A": [1, 2]})
df2 = pd.DataFrame({"B": [3, 4]})

In [210]:
df1

A
0  1
1  2

In [211]:
df2

B
0  3
1  4

In [212]:
df1 + df2

A   B
0 NaN NaN
1 NaN NaN

#### Arithmetic methods with fill values

In [213]:
df1 = pd.DataFrame(np.arange(12.).reshape((3, 4)),
                   columns=list("abcd"))
df2 = pd.DataFrame(np.arange(20.).reshape((4, 5)),
                   columns=list("abcde"))

In [214]:
df2.loc[1, "b"] = np.nan

In [215]:
df1

a    b     c     d
0  0.0  1.0   2.0   3.0
1  4.0  5.0   6.0   7.0
2  8.0  9.0  10.0  11.0

In [216]:
df2

a     b     c     d     e
0   0.0   1.0   2.0   3.0   4.0
1   5.0   NaN   7.0   8.0   9.0
2  10.0  11.0  12.0  13.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [217]:
df1 + df2

a     b     c     d   e
0   0.0   2.0   4.0   6.0 NaN
1   9.0   NaN  13.0  15.0 NaN
2  18.0  20.0  22.0  24.0 NaN
3   NaN   NaN   NaN   NaN NaN

In [218]:
df1.add(df2, fill_value=0)

a     b     c     d     e
0   0.0   2.0   4.0   6.0   4.0
1   9.0   5.0  13.0  15.0   9.0
2  18.0  20.0  22.0  24.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [219]:
1 / df1

a         b         c         d
0    inf  1.000000  0.500000  0.333333
1  0.250  0.200000  0.166667  0.142857
2  0.125  0.111111  0.100000  0.090909

In [220]:
df1.rdiv(1)

a         b         c         d
0    inf  1.000000  0.500000  0.333333
1  0.250  0.200000  0.166667  0.142857
2  0.125  0.111111  0.100000  0.090909

In [221]:
df1.reindex(columns=df2.columns, fill_value=0)

a    b     c     d  e
0  0.0  1.0   2.0   3.0  0
1  4.0  5.0   6.0   7.0  0
2  8.0  9.0  10.0  11.0  0

Flexible arithmetic methods

* add, radd	Methods for addition (+)
* sub, rsub	Methods for subtraction (-)
* div, rdiv	Methods for division (/)
* floordiv, rfloordiv	Methods for floor division (//)
* mul, rmul	Methods for multiplication (*)
* pow, rpow	Methods for exponentiation (**)

### Operations between DataFrame and Series

In [222]:
arr = np.arange(12.).reshape((3,4))

In [223]:
arr

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [224]:
arr[0]

array([0., 1., 2., 3.])

In [225]:
arr - arr[0]

array([[0., 0., 0., 0.],
       [4., 4., 4., 4.],
       [8., 8., 8., 8.]])

In [227]:
frame = pd.DataFrame(np.arange(12.).reshape((4,3)),
                     columns=list("bde"),
                     index=["Utah", "Ohio", "Texas", "Oregon"])

In [228]:
series = frame.iloc[0]

In [229]:
frame

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [230]:
series

b    0.0
d    1.0
e    2.0
Name: Utah, dtype: float64

In [231]:
frame - series

b    d    e
Utah    0.0  0.0  0.0
Ohio    3.0  3.0  3.0
Texas   6.0  6.0  6.0
Oregon  9.0  9.0  9.0

In [232]:
series2 = pd.Series(np.arange(3), index=["b", "e", "f"])

In [233]:
series2

b    0
e    1
f    2
dtype: int64

In [234]:
frame + series2

b   d     e   f
Utah    0.0 NaN   3.0 NaN
Ohio    3.0 NaN   6.0 NaN
Texas   6.0 NaN   9.0 NaN
Oregon  9.0 NaN  12.0 NaN

In [236]:
series3 = frame["d"]

In [237]:
frame

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [238]:
series3

Utah       1.0
Ohio       4.0
Texas      7.0
Oregon    10.0
Name: d, dtype: float64

In [239]:
frame.sub(series3, axis="index")

b    d    e
Utah   -1.0  0.0  1.0
Ohio   -1.0  0.0  1.0
Texas  -1.0  0.0  1.0
Oregon -1.0  0.0  1.0

## Function Application and Mapping

### Sorting and Ranking

Tie-breaking methods with rank

## Axis Indexes with Duplicate Labels

# 5.3 Summarizing and Computing Descriptive Statistics

Options for reduction methods

Descriptive and summary statistics

### Correlation and Covariance

### Unique Values, Value Counts, and Membership

Unique, values counts, and set membership methods